In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
data=pd.read_csv("Company_Data.csv")
df=pd.DataFrame(data)
df.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [5]:
df.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [6]:
label_encoder = preprocessing.LabelEncoder() 
df[('ShelveLoc')]= label_encoder.fit_transform(df[('ShelveLoc')]) 
df[('Urban')]=label_encoder.fit_transform(df[('Urban')])
df[('US')]= label_encoder.fit_transform(df[('US')]) 
df.head()

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0   9.50        138      73           11         276    120          0   42   
1  11.22        111      48           16         260     83          1   65   
2  10.06        113      35           10         269     80          2   59   
3   7.40        117     100            4         466     97          2   55   
4   4.15        141      64            3         340    128          0   38   

   Education  Urban  US  
0         17      1   1  
1         10      1   1  
2         12      1   1  
3         14      1   1  
4         13      1   0

In [7]:
df['Sales']=df['Sales'].map(lambda x:1 if x>8 else 0)
df['Sales']

0      1
1      1
2      1
3      0
4      0
      ..
395    1
396    0
397    0
398    0
399    1
Name: Sales, Length: 400, dtype: int64

In [8]:
df.dtypes

Sales          int64
CompPrice      int64
Income         int64
Advertising    int64
Population     int64
Price          int64
ShelveLoc      int32
Age            int64
Education      int64
Urban          int32
US             int32
dtype: object

In [9]:
from sklearn.preprocessing import StandardScaler 
scaler=StandardScaler()
scaler_x=scaler.fit_transform(df)

In [10]:
df.describe()

Sales   CompPrice      Income  Advertising  Population  \
count  400.000000  400.000000  400.000000   400.000000  400.000000   
mean     0.410000  124.975000   68.657500     6.635000  264.840000   
std      0.492449   15.334512   27.986037     6.650364  147.376436   
min      0.000000   77.000000   21.000000     0.000000   10.000000   
25%      0.000000  115.000000   42.750000     0.000000  139.000000   
50%      0.000000  125.000000   69.000000     5.000000  272.000000   
75%      1.000000  135.000000   91.000000    12.000000  398.500000   
max      1.000000  175.000000  120.000000    29.000000  509.000000   

            Price   ShelveLoc         Age   Education       Urban          US  
count  400.000000  400.000000  400.000000  400.000000  400.000000  400.000000  
mean   115.795000    1.307500   53.322500   13.900000    0.705000    0.645000  
std     23.676664    0.833475   16.200297    2.620528    0.456614    0.479113  
min     24.000000    0.000000   25.000000   10.000000    0.000000    0.000000  
25%    100.000000    1.000000   39.750000   12.000000    0.000000    0.000000  
50%    117.000000    2.000000   54.500000   14.000000    1.000000    1.000000  
75%    131.000000    2.000000   66.000000   16.000000    1.000000    1.000000  
max    191.000000    2.000000   80.000000   18.000000    1.000000    1.000000

##### x=input variable and y=target variable

In [11]:
x=df.iloc[:,1:11]
y=df['Sales']

In [12]:
x.head()

CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0        138      73           11         276    120          0   42   
1        111      48           16         260     83          1   65   
2        113      35           10         269     80          2   59   
3        117     100            4         466     97          2   55   
4        141      64            3         340    128          0   38   

   Education  Urban  US  
0         17      1   1  
1         10      1   1  
2         12      1   1  
3         14      1   1  
4         13      1   0

In [13]:
y.head()

0    1
1    1
2    1
3    0
4    0
Name: Sales, dtype: int64

In [14]:
df['Sales'].unique()

array([1, 0], dtype=int64)

In [15]:
df.Sales.value_counts()

0    236
1    164
Name: Sales, dtype: int64

In [16]:
colnames = list(df.columns)
colnames

['Sales',
 'CompPrice',
 'Income',
 'Advertising',
 'Population',
 'Price',
 'ShelveLoc',
 'Age',
 'Education',
 'Urban',
 'US']

### Slipitting data into train and test 

In [17]:
x_train, x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=12)

In [18]:
# fit model no training data
model = XGBClassifier()
model.fit(x_train, y_train)


c:\users\damanjeet kaur.laptop-b5chj9sc\appdata\local\programs\python\python37\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[02:56:25] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

### Building Model

In [19]:
model_gini = DecisionTreeClassifier(criterion='gini', max_depth=6)

In [20]:
model_gini.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6)

In [21]:
y_train_pred=model_gini.predict(x_train)

In [22]:
y_test_pred=model_gini.predict(x_test)

### Checking accuracy for train data

In [23]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_train,y_train_pred)

0.940625

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,y_train_pred)

array([[186,   1],
       [ 18, 115]], dtype=int64)

### Checking accuracy for test data

In [26]:
accuracy_score(y_test,y_test_pred)

0.6625

In [27]:
confusion_matrix(y_test,y_test_pred)

array([[38, 11],
       [16, 15]], dtype=int64)